namespace Лаба_4
{
    partial class AddClientForm{
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing){
            if (disposing && (components != null)){
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent(){
            this.comboBoxClientType = new System.Windows.Forms.ComboBox();
            this.textBoxName = new System.Windows.Forms.TextBox();
            this.textBoxBaseCost = new System.Windows.Forms.TextBox();
            this.comboBoxPricingStrategy = new System.Windows.Forms.ComboBox();
            this.textBoxAdditionalInfo = new System.Windows.Forms.TextBox();
            this.labelAdditionalInfo = new System.Windows.Forms.Label();
            this.textBoxDiscount = new System.Windows.Forms.TextBox();
            this.labelDiscount = new System.Windows.Forms.Label();
            this.buttonOK = new System.Windows.Forms.Button();
            this.buttonCancel = new System.Windows.Forms.Button();
            this.SuspendLayout();
            this.comboBoxClientType.FormattingEnabled = true;
            this.comboBoxClientType.Items.AddRange(new object[] {"Обычный клиент","VIP клиент","Корпоративный клиент"});
            this.comboBoxClientType.Location = new System.Drawing.Point(120, 20);
            this.comboBoxClientType.Name = "comboBoxClientType";
            this.comboBoxClientType.Size = new System.Drawing.Size(200, 21);
            this.comboBoxClientType.TabIndex = 0;
            this.comboBoxClientType.SelectedIndexChanged += new System.EventHandler(this.comboBoxClientType_SelectedIndexChanged);
            this.textBoxName.Location = new System.Drawing.Point(120, 50);
            this.textBoxName.Name = "textBoxName";
            this.textBoxName.Size = new System.Drawing.Size(200, 20);
            this.textBoxName.TabIndex = 1;
            this.textBoxBaseCost.Location = new System.Drawing.Point(120, 80);
            this.textBoxBaseCost.Name = "textBoxBaseCost";
            this.textBoxBaseCost.Size = new System.Drawing.Size(200, 20);
            this.textBoxBaseCost.TabIndex = 2;
            this.comboBoxPricingStrategy.FormattingEnabled = true;
            this.comboBoxPricingStrategy.Items.AddRange(new object[] {"Стандартная цена","Фиксированная скидка","Процентная скидка"});
            this.comboBoxPricingStrategy.Location = new System.Drawing.Point(120, 110);
            this.comboBoxPricingStrategy.Name = "comboBoxPricingStrategy";
            this.comboBoxPricingStrategy.Size = new System.Drawing.Size(200, 21);
            this.comboBoxPricingStrategy.TabIndex = 3;
            this.comboBoxPricingStrategy.SelectedIndexChanged += new System.EventHandler(this.comboBoxPricingStrategy_SelectedIndexChanged);
            this.textBoxAdditionalInfo.Location = new System.Drawing.Point(120, 140);
            this.textBoxAdditionalInfo.Name = "textBoxAdditionalInfo";
            this.textBoxAdditionalInfo.Size = new System.Drawing.Size(200, 20);
            this.textBoxAdditionalInfo.TabIndex = 4;
            this.textBoxAdditionalInfo.Visible = false; 
            this.labelAdditionalInfo.AutoSize = true;
            this.labelAdditionalInfo.Location = new System.Drawing.Point(20, 143);
            this.labelAdditionalInfo.Name = "labelAdditionalInfo";
            this.labelAdditionalInfo.Size = new System.Drawing.Size(70, 13);
            this.labelAdditionalInfo.TabIndex = 5;
            this.labelAdditionalInfo.Text = "Уровень VIP:";
            this.labelAdditionalInfo.Visible = false;
            this.textBoxDiscount.Location = new System.Drawing.Point(120, 170);
            this.textBoxDiscount.Name = "textBoxDiscount";
            this.textBoxDiscount.Size = new System.Drawing.Size(200, 20);
            this.textBoxDiscount.TabIndex = 6;
            this.textBoxDiscount.Visible = false;
            this.labelDiscount.AutoSize = true;
            this.labelDiscount.Location = new System.Drawing.Point(20, 173);
            this.labelDiscount.Name = "labelDiscount";
            this.labelDiscount.Size = new System.Drawing.Size(80, 13);
            this.labelDiscount.TabIndex = 7;
            this.labelDiscount.Text = "Размер скидки:";
            this.labelDiscount.Visible = false;
            this.buttonOK.Location = new System.Drawing.Point(120, 210);
            this.buttonOK.Name = "buttonOK";
            this.buttonOK.Size = new System.Drawing.Size(90, 30);
            this.buttonOK.TabIndex = 8;
            this.buttonOK.Text = "OK";
            this.buttonOK.UseVisualStyleBackColor = true;
            this.buttonOK.Click += new System.EventHandler(this.buttonOK_Click);
            this.buttonCancel.Location = new System.Drawing.Point(230, 210);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new System.Drawing.Size(90, 30);
            this.buttonCancel.TabIndex = 9;
            this.buttonCancel.Text = "Отмена";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.buttonCancel.Click += new System.EventHandler(this.buttonCancel_Click);
            System.Windows.Forms.Label label1 = new System.Windows.Forms.Label();
            label1.AutoSize = true;
            label1.Location = new System.Drawing.Point(20, 23);
            label1.Name = "label1";
            label1.Size = new System.Drawing.Size(79, 13);
            label1.TabIndex = 10;
            label1.Text = "Тип клиента:";
            System.Windows.Forms.Label label2 = new System.Windows.Forms.Label();
            label2.AutoSize = true;
            label2.Location = new System.Drawing.Point(20, 53);
            label2.Name = "label2";
            label2.Size = new System.Drawing.Size(32, 13);
            label2.TabIndex = 11;
            label2.Text = "Имя:";
            System.Windows.Forms.Label label3 = new System.Windows.Forms.Label();
            label3.AutoSize = true;
            label3.Location = new System.Drawing.Point(20, 83);
            label3.Name = "label3";
            label3.Size = new System.Drawing.Size(92, 13);
            label3.TabIndex = 12;
            label3.Text = "Базовая стоимость:";
            System.Windows.Forms.Label label4 = new System.Windows.Forms.Label();
            label4.AutoSize = true;
            label4.Location = new System.Drawing.Point(20, 113);
            label4.Name = "label4";
            label4.Size = new System.Drawing.Size(58, 13);
            label4.TabIndex = 13;
            label4.Text = "Стратегия:";
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(350, 260);
            this.Controls.Add(this.buttonCancel);
            this.Controls.Add(this.buttonOK);
            this.Controls.Add(this.labelDiscount);
            this.Controls.Add(this.textBoxDiscount);
            this.Controls.Add(this.labelAdditionalInfo);
            this.Controls.Add(this.textBoxAdditionalInfo);
            this.Controls.Add(this.comboBoxPricingStrategy);
            this.Controls.Add(this.textBoxBaseCost);
            this.Controls.Add(this.textBoxName);
            this.Controls.Add(this.comboBoxClientType);
            this.Controls.Add(label1);
            this.Controls.Add(label2);
            this.Controls.Add(label3);
            this.Controls.Add(label4);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "AddClientForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Добавление клиента";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.ComboBox comboBoxClientType;
        private System.Windows.Forms.TextBox textBoxName;
        private System.Windows.Forms.TextBox textBoxBaseCost;
        private System.Windows.Forms.ComboBox comboBoxPricingStrategy;
        private System.Windows.Forms.TextBox textBoxAdditionalInfo;
        private System.Windows.Forms.Label labelAdditionalInfo;
        private System.Windows.Forms.TextBox textBoxDiscount;
        private System.Windows.Forms.Label labelDiscount;
        private System.Windows.Forms.Button buttonOK;
        private System.Windows.Forms.Button buttonCancel;
    }
}